bugs:
  1: alife.agents.evolution/SimpleEvolver/{'H':10}
  2: alife.agents.evolution/SimpleEvolver/{'H':-10}
  3: alife.agents.evolution/CognitiveEnvolver/{'ObservationSystem':'SinglePropositionSystem','BeliefRevisionSystem':'ConditionalBeliefRevision',
    'WorkingMemorySystem':'WorkingMemoryWithEvidence','DecisionMakingSystem':'HumanLikeDecisionMakingUnderUncertaintySystem',
    'MentalMap':'True','ObservationSystem_Args':[], 'BeliefRevisionSystem_Args':['False'],
    'WorkingMemorySystem_Args':['RANKING',25], 'DecisionMakingSystem_Args':[0.2, 0.5,
    'RANKING', 'True', 'True', 5, 14,14,15,7, 7, 7, 7],'CommunicationSystem_Args':['False',
    10, 'RANKING'],'yml_file':'Config9.yml'}
log_file:
  name: Config9.csv
