bugs:
  1: alife.agents.evolution/SimpleEvolver/{'H':10}
  2: alife.agents.evolution/SimpleEvolver/{'H':-10}
  3: alife.agents.evolution/CognitiveEnvolver/{'ObservationSystem':'SinglePropositionSystem','BeliefRevisionSystem':'FormalBeliefRevision',
    'WorkingMemorySystem':'WorkingMemoryWithEvidence','DecisionMakingSystem':'HumanLikeDecisionMakingUnderUncertaintySystem',
    'MentalMap':'True','ObservationSystem_Args':[], 'BeliefRevisionSystem_Args':['False'],
    'WorkingMemorySystem_Args':['EVIDENCE',66], 'DecisionMakingSystem_Args':[0.2,
    0.5, 'EVIDENCE', 'True', 'True', 5,  14,14,15,7, 7, 7, 7],'CommunicationSystem_Args':['False',
    10, 'EVIDENCE'],'yml_file':'Config4.yml'}
log_file:
  name: Config4.csv
