bugs:
  1: alife.agents.evolution/SimpleEvolver/{'H':10}
  2: alife.agents.evolution/SimpleEvolver/{'H':-10}
  3: alife.agents.evolution/CognitiveEnvolver/{'ObservationSystem':'MultiplePropositionSystem','BeliefRevisionSystem':'ProbabilityBeliefRevision',
    'WorkingMemorySystem':'WorkingMemoryWithEvidence','DecisionMakingSystem':'HumanLikeDecisionMakingUnderUncertaintySystem',
    'MentalMap':'True','ObservationSystem_Args':[], 'BeliefRevisionSystem_Args':['False','False'],
    'WorkingMemorySystem_Args':['PROBABILITY',100], 'DecisionMakingSystem_Args':[0.2,
    0.5, 'PROBABILITY', 'True', 'True', 5,  14,14,15,7, 7, 7, 7],'CommunicationSystem_Args':['False',
    10, 'PROBABILITY'],'yml_file':'Config12.yml'}
log_file:
  name: Config12.csv
